(define (oppy op1)
    (lambda (x)
        (lambda (op2)
            (lambda (y)
                (lambda (z)
                    (op1 x (op2 y z))
                )
            )
        )
    )
)

(inspect (- 1 (** 2 3)))
(inspect (((((oppy -) 1) **) 2) 3))
